name: Super-Linter

on: push

jobs:
  super-lint:
    name: Lint Code
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read

      statuses: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Run Super-Linter
        uses: super-linter/super-linter@v7.1.0
        env:
          DEFAULT_BRANCH: main
          FIX_MARKDOWN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
